name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:    
  solution: src/DecimalChecker.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $solution
    - name: Build
      run: dotnet build $solution --no-restore
    - name: Test
      run: dotnet test $solution --no-build --verbosity normal
    - name: Pack
      run: dotnet pack $solution --no-build --include-source --output pkgs
    - name: Upload Package as a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: package
        path: pkgs
